#!/bin/sh
#
# hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# 

set -eu

result=0

msg_color_error='\033[31m'
msg_color_success='\033[32m'
msg_color_warning='\033[33m'
msg_color_none='\033[0m'


script_path=$(git rev-parse --show-toplevel)/.githooks/pre-commit-rules

#use shell
sh $script_path/OBJC_ASSOCIATION_ASSIGN_checker.sh

#use ruby
ruby $script_path/image_name_checker.rb


echo "${msg_color_success}commit check success ${msg_color_none} \n"

exit $result