#!/bin/sh
#
# hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# 

result=0

msg_color_error='\033[1;31m'
msg_color_yellow='\033[0;33m'
msg_color_none='\033[0m' # No Color

echo "${msg_color_yellow}Begin commit check ...${msg_color_none} \n"
test_pattern='[a-z]'
if git diff-index -p -M --cached HEAD -- '*.m' | grep '^+' | egrep "$test_pattern" >/dev/null 2>&1
then
  echo "包含不安全的format方法:$test_pattern" >&2
  echo "请修改后提交." >&2
  echo '----' >&2
  git grep -E "$test_pattern" '*.h' '*.m'  >&2
  echo '----' >&2
  result=1
else 
  echo "commit检查通过." >&1
fi


exit $result